# Generated by Django 5.1.6 on 2025-02-08 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pet', models.CharField(max_length=255)),
                ('tipo_pet', models.CharField(choices=[('Canino', 'Canino'), ('Felino', 'Felino'), ('Bovino', 'Bovino'), ('Equino', 'Equino'), ('Aves', 'Aves'), ('Silvestres', 'Silvestres'), ('Outros', 'Outros')], max_length=50)),
                ('raca', models.CharField(max_length=255)),
                ('genero', models.CharField(choices=[('Macho', 'Macho'), ('Fêmea', 'Fêmea')], max_length=10)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente_software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='clientes.clientesoftware')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateTimeField()),
                ('veterinario', models.CharField(max_length=255)),
                ('motivo', models.TextField()),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('prescricao', models.TextField(blank=True, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='pets.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_vacina', models.CharField(max_length=255)),
                ('data_aplicacao', models.DateField()),
                ('proxima_dose', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinas', to='pets.pet')),
            ],
        ),
        migrations.CreateModel(
            name='TutorPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio_tutela', models.DateField()),
                ('data_fim_tutela', models.DateField(blank=True, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutores', to='pets.pet')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets_tutor', to='clientes.clientesoftware')),
            ],
            options={
                'unique_together': {('tutor', 'pet')},
            },
        ),
    ]
