# Generated by Django 5.1.6 on 2025-02-08 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_tutor'),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorpet',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets_tutor', to='clientes.tutor'),
        ),
    ]
