# Generated by Django 5.1.6 on 2025-02-08 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_usuario_email_alter_usuario_nome_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cliente_software',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='clientes.clientesoftware'),
        ),
    ]
